[build]
  command = "make build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-apt"
  version = "1.0.0"

[build.environment]
  SYSTEM_PACKAGE_MANAGER = "apt-get"
  SYSTEM_PACKAGES = ["clang"]
